services:
  app:
    build: .
    container_name: lms-app
    volumes:
      - ./src:/usr/src/app/src # <---- this
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
